### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by Masayuki-Abe-Git** [Masayuki-Abe-Git/chat-space#10]
IPアドレス
18.180.75.171

**Comment by mo1015** [comment]
阿部さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**○サイドバーのグループの位置を修正しましょう
○投稿メッセージの表示間隔を修正しましょう
○メッセージ送信フォームの位置を修正しましょう**

<img width="1440" alt="修正" src="https://user-images.githubusercontent.com/62644781/85240984-2b5e6000-b475-11ea-8b8c-9bb70a021bcb.png">

↓カリキュラム画像を参考に余白等を修正しましょう
<img width="591" alt="サイドバー見本" src="https://user-images.githubusercontent.com/62644781/85240994-32856e00-b475-11ea-9b30-6a216c371d32.png">
<img width="591" alt="投稿欄見本" src="https://user-images.githubusercontent.com/62644781/85240998-3913e580-b475-11ea-887f-960d8c222538.png">

<img width="691" alt="投稿フォーム見本" src="https://user-images.githubusercontent.com/62644781/85241002-3ca76c80-b475-11ea-9076-77e903224ef5.png">

**○チャットグループ編集ページの見た目を修正しましょう**
<img width="1440" alt="修正2" src="https://user-images.githubusercontent.com/62644781/85241045-606ab280-b475-11ea-9dca-834e4e462e6b.png">
↓見本
<img width="1088" alt="スクリーンショット 2020-06-22 10 45 16" src="https://user-images.githubusercontent.com/62644781/85241075-855f2580-b475-11ea-9670-1847a0c664e7.png">

**○今いるグループのチャットグループ編集ページに飛ぶようにしましょう**
<img width="1440" alt="修正" src="https://user-images.githubusercontent.com/62644781/85241345-75941100-b476-11ea-9588-f4017a775fea.png">
<img width="1021" alt="修正2" src="https://user-images.githubusercontent.com/62644781/85241347-788f0180-b476-11ea-8a42-f2c476a428d4.png">


修正でき次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by Masayuki-Abe-Git** [comment]
修正しました、確認お願いします。

**Comment by Masayuki-Abe-Git** [comment]
> IPアドレス
> 18.180.75.171

**Comment by mutorisa** [comment]
修正後、再度ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！！

⭐️今後実装に関するご質問がございましたら、メンターに相談いただきますようお願いします。
